name: "Tests"
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        id: open-pr
        with:
          source_branch: "test"
          destination_branch: "main"
          github_token: ${{ secrets.GH_TOKEN }}
          pr_title: Promote homolog to production
          pr_body: teste

      - name: Update PR
        id: get_prs
        uses: ./
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          destination_branch: main
          source_branch: test
          pr_title: Promote homolog to production taylors version
          pr_body: update
          pr_reviewers: "alexiabalionis"
          pr_team_reviewers: ""
